
SELECT * FROM usuarios WHERE NUMDOC_USUARIOS='1827842630';
SELECT* FROM usuarios WHERE NOMBRE_USUARIOS LIKE 'Gabriel';
SELECT* FROM usuarios WHERE NOMBRE_USUARIOS LIKE '%MARIA%';
SELECT* FROM usuarios WHERE NOMBRE_USUARIOS LIKE 'CA%' AND DIRECCIÓN_USUARIOS LIKE '%CARRERA%';
SELECT* FROM usuarios WHERE NOMBRE_USUARIOS LIKE '%Juan%' OR NOMBRE_USUARIOS LIKE '%juliana%' OR NOMBRE_USUARIOS LIKE '%Oscar%';
