INSERT INTO usuarios(ID_USUARIOS,NOMBRE_USUARIOS,APELLIDO_USUARIOS,TIPODOC_USUARIOS,NUMDOC_USUARIOS,DIRECCIÓN_USUARIOS,TELEFONO_USUARIO,CORREO_USUARIO,CONTRASEÑA_USUARIO,ID_ROLES_USUARIOS,ROLES_USUARIOS) VALUES('25','Carlos','Ramirez','CC','1199901437','Carrera 12 # 63-184','312-463-7570','Carlos.Ramirez@gmail.com','1199901437cr','3','domiciliario');
INSERT INTO roles(ID_ROLES,NOMBRE_ROL) VALUES('4','Usuario');
INSERT INTO ordenes(ID_ORDENES,EPS_ORDEN,USUARIOS_PACIENTE) VALUES('11','SANITAS','25');
INSERT INTO medicamentos(ID_MEDICAMENTOS,NOMBRE_MEDICAMENTOS,DESCRIPCIÓN_MEDICAMENTOS,FRECUENCIA_MEDICAMENTOS,CANTIDAD_MEDICAMENTO) VALUES('11','Aspirina','Inhibidor de la síntesis de prostaglandinas, reduciendo la inflamación y el dolor','1 unidad cada 6 hora(s) por 10 días','40 (cuarenta) tabletas');
INSERT INTO ordenes_has_medicamentos(ID_MEDICAMENTO_POR_ORDEN,ID_ORDENES,ID_MEDICAMENTOS) VALUES('11','11','11');
INSERT INTO inventario(ID_INVENTARIO,FECHA_ENTRADA_INVENTARIO,FECHA_SALIDA_INVENTARIO,ID_MEDICAMENTOS,STOCK_INVENTARIO) VALUES('11','45328','45353','11','25');
INSERT INTO privilegios(ID_PRIVILEGIOS,DESCRIPCIÓN_PRIVILEGIOS) VALUES('4','DELETE');
INSERT INTO usuarios_has_privilegios(ID_PRIVILEGIO_USUARIO,ID_USUARIOS,ID_PRIVILEGIOS) VALUES('17','17','1');
INSERT INTO domicilio(ID_DOMICILIO,UBICACION_DOMICILIO,ESTADO_DOMICILIO,ID_VEHÍCULO,ID_ORDENES) VALUES('11','Calle 14 #15-43','En camino','11','11');
INSERT INTO vehículo(ID_VEHÍCULO,COLOR_VEHÍCULO,MARCA_VEHÍCULO,PLACA_VEHÍCULO,TIPO_VEHÍCULO,ID_USUARIOS) VALUES('11','Verde','Suzuki','XAS-24D','Moto','25');


DELETE FROM domicilio WHERE ID_ORDENES=11;
DELETE FROM ordenes_has_medicamentos WHERE ID_ORDENES=11;
DELETE FROM ordenes WHERE USUARIOS_PACIENTE=25;
DELETE FROM vehículo WHERE ID_USUARIOS=25;
DELETE FROM usuarios WHERE ID_USUARIOS=25;
DELETE FROM usuarios_has_privilegios WHERE ID_PRIVILEGIO_USUARIO=17;
DELETE FROM roles WHERE ID_ROLES=4;
DELETE FROM privilegios WHERE ID_PRIVILEGIOS=4;
DELETE FROM medicamentos WHERE ID_MEDICAMENTOS=11;
DELETE FROM inventario WHERE ID_MEDICAMENTOS=11;