SELECT * FROM usuarios WHERE ID_USUARIOS='1';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='1';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='3';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='4';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='6';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='8';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='9';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='11';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='13';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='16';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='17';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='18';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='20';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='22';
UPDATE usuarios SET GENERO_USUARIOS='femenino' WHERE ID_USUARIOS='23';

UPDATE usuarios SET GENERO_USUARIOS='masculino' WHERE ID_USUARIOS='2';
UPDATE usuarios SET GENERO_USUARIOS='masculino' WHERE ID_USUARIOS='5';
UPDATE usuarios SET GENERO_USUARIOS='masculino' WHERE ID_USUARIOS='7';
UPDATE usuarios SET GENERO_USUARIOS='masculino' WHERE ID_USUARIOS='10';
UPDATE usuarios SET GENERO_USUARIOS='masculino' WHERE ID_USUARIOS='12';
UPDATE usuarios SET GENERO_USUARIOS='masculino' WHERE ID_USUARIOS='14';
UPDATE usuarios SET GENERO_USUARIOS='masculino' WHERE ID_USUARIOS='15';
UPDATE usuarios SET GENERO_USUARIOS='masculino' WHERE ID_USUARIOS='19';
UPDATE usuarios SET GENERO_USUARIOS='masculino' WHERE ID_USUARIOS='21';
UPDATE usuarios SET GENERO_USUARIOS='masculino' WHERE ID_USUARIOS='24';

UPDATE domicilio SET ESTADO_DOMICILIO='ENTREGADO' WHERE UBICACION_DOMICILIO='Avenida 6 #45-67';

UPDATE ordenes SET EPS_ORDEN='SANITAS' WHERE ID_ORDENES='5';